version: '3.0'

services:
  nginx:
    build:
        context: ./docker/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
      - ./app/:/var/www/
    networks:
      - default

  app:
    build:
      context: ./docker/php
    environment:
      PHP_IDE_CONFIG : "serverName=localhost"
    expose:
      - 9000
      - 9003
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./app/:/var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  db:
    image: postgres:13.3
    volumes:
      - ./docker/database/pgsql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "laravel"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - default



networks:
  default:
    driver: bridge
